"""empty message

Revision ID: 52a294c90f2a
Revises: 75b16eb1356f
Create Date: 2018-07-06 10:35:36.084817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a294c90f2a'
down_revision = '75b16eb1356f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwd', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'passwd')
    # ### end Alembic commands ###
