# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
    ]
